version: '2'
services:
    app:
        image: harshwebkorps/dockerapp_app:v4
        volumes:
            - ".:/app"
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        image: postgres:latest
        container_name: my_postgres
        environment:
            POSTGRES_DB: docker-app
            POSTGRES_USER: social_network
            POSTGRES_PASSWORD: password1
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: