apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
  - name: two-tier-app-ctr
    image: harshwebkorps/dockerapp_app:v4
    ports:
      - containerPort: 3000
    imagePullPolicy: Always
    
